// Read-only exercise library, loaded once from the static JSON asset
// generated by scripts/build-exercise-data.mjs (free-exercise-db plus a
// handful of curated speed/agility/conditioning drills).
let cache = null;

export async function loadExercises() {
  if (cache) return cache;
  const res = await fetch(`${import.meta.env.BASE_URL}exercises.json`);
  cache = await res.json();
  return cache;
}

export async function getExercises({ search = '', category = '', tag = '', equipment = '', difficulty = '' } = {}) {
  const all = await loadExercises();
  const q = search.trim().toLowerCase();
  return all
    .filter((ex) => {
      if (q && !ex.name.toLowerCase().includes(q)) return false;
      if (category && ex.category !== category) return false;
      if (equipment && ex.equipment !== equipment) return false;
      if (difficulty && ex.difficulty !== difficulty) return false;
      if (tag && !ex.tags.includes(tag)) return false;
      return true;
    })
    .sort((a, b) => a.name.localeCompare(b.name))
    .slice(0, 200);
}

export async function getExercise(id) {
  const all = await loadExercises();
  return all.find((ex) => ex.id === id) || null;
}

export async function getExerciseMap() {
  const all = await loadExercises();
  return new Map(all.map((ex) => [ex.id, ex]));
}
